import type { WeaponStats } from "./weaponStats";

/** Lots of weak bullets. Recoil builds up fast during long bursts. */
export const MACHINE_GUN: WeaponStats = {
  name: "Machine Gun",
  shortName: "MG",
  damageType: "bullet",
  damage: 4,
  fireMode: "auto",
  fireRate: 12,
  magazine: 40,
  reloadTime: 2.0,
  pellets: 1,
  spread: 4,
  recoil: 1.2,
  maxRecoil: 12,
  recoilRecovery: 25,
  projectileSpeed: 1000,
  projectileSize: 5,
  range: 650,
  knockback: 15,
  blastRadius: 0,
};

/** Short-range burst of pellets. */
export const SHOTGUN: WeaponStats = {
  name: "Shotgun",
  shortName: "SG",
  damageType: "bullet",
  damage: 6,
  fireMode: "semi",
  fireRate: 1.4,
  magazine: 6,
  reloadTime: 2.2,
  pellets: 8,
  spread: 26,
  recoil: 6,
  maxRecoil: 10,
  recoilRecovery: 20,
  projectileSpeed: 900,
  projectileSize: 5,
  range: 650,
  knockback: 35,
  blastRadius: 0,
};

/** Fast, accurate energy bolts. */
export const ENERGY_RIFLE: WeaponStats = {
  name: "Energy Rifle",
  shortName: "ER",
  damageType: "energy",
  damage: 14,
  fireMode: "semi",
  fireRate: 2.5,
  magazine: 8,
  reloadTime: 1.8,
  pellets: 1,
  spread: 1,
  recoil: 3,
  maxRecoil: 8,
  recoilRecovery: 12,
  projectileSpeed: 1600,
  projectileSize: 6,
  range: 900,
  knockback: 40,
  blastRadius: 0,
};

/** Slow rockets that explode on impact or at max range. Heavy: bipedal legs self-stagger after each shot. */
export const ROCKET_LAUNCHER: WeaponStats = {
  name: "Rocket Launcher",
  shortName: "RL",
  damageType: "explosive",
  damage: 30,
  fireMode: "semi",
  fireRate: 0.8,
  magazine: 3,
  reloadTime: 3.0,
  pellets: 1,
  spread: 2,
  recoil: 5,
  maxRecoil: 8,
  recoilRecovery: 10,
  projectileSpeed: 520,
  projectileSize: 12,
  range: 800,
  knockback: 420,
  blastRadius: 90,
  brace: { recovery: 0.6 },
};
